-- AlterTable
ALTER TABLE "Order" ADD COLUMN "giftCost" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN "isGift" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN "unitCost" DOUBLE PRECISION;
