import type {
  Product,
  SaleSnapshot,
  SettlementSnapshot,
  VoucherFaceTier,
} from './types';

export const LOW_STOCK_AT = 3;

export const PRODUCTS: Product[] = [
  {
    productId: 'prod-beef',
    name: '原味牛肉條',
    variants: [
      {
        skuId: 'sku-beef-80',
        sku: 'FMT-BEEF-80',
        specLabel: '原味 80g',
        listPriceTwd: 180,
        availableQty: 12,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 6,
      },
      {
        skuId: 'sku-beef-150',
        sku: 'FMT-BEEF-150',
        specLabel: '原味 150g',
        listPriceTwd: 280,
        availableQty: 3,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 8,
      },
      {
        skuId: 'sku-beef-300',
        sku: 'FMT-BEEF-300',
        specLabel: '原味 300g',
        listPriceTwd: 480,
        availableQty: 0,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 4,
      },
    ],
  },
  {
    productId: 'prod-chicken',
    name: '雞肉凍乾',
    variants: [
      {
        skuId: 'sku-chkn-50',
        sku: 'FMT-CHKN-50',
        specLabel: '袋裝 50g',
        listPriceTwd: 220,
        availableQty: 8,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 6,
      },
      {
        skuId: 'sku-chkn-100',
        sku: 'FMT-CHKN-100',
        specLabel: '袋裝 100g',
        listPriceTwd: 390,
        availableQty: 2,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 5,
      },
    ],
  },
  {
    productId: 'prod-salmon',
    name: '鮭魚薄片',
    variants: [
      {
        skuId: 'sku-slmn-1',
        sku: 'FMT-SLMN-01',
        specLabel: '單包',
        listPriceTwd: 160,
        availableQty: 0,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 10,
      },
    ],
  },
  {
    productId: 'prod-cheese',
    name: '起司潔牙棒',
    variants: [
      {
        skuId: 'sku-chee-s',
        sku: 'FMT-CHEE-S',
        specLabel: '小型犬',
        listPriceTwd: 140,
        availableQty: 15,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 4,
      },
      {
        skuId: 'sku-chee-m',
        sku: 'FMT-CHEE-M',
        specLabel: '中型犬',
        listPriceTwd: 160,
        availableQty: 1,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 6,
      },
      {
        skuId: 'sku-chee-l',
        sku: 'FMT-CHEE-L',
        specLabel: '大型犬',
        listPriceTwd: 180,
        availableQty: 6,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 4,
      },
    ],
  },
];

export const SALES: SaleSnapshot[] = [
  {
    saleId: 'sale-cash-open',
    soldAtLabel: '2026-07-18 10:24',
    channel: 'merchant_collected',
    channelLabel: '店內收款',
    pickupLabel: null,
    statusLabel: '已完成（示意）',
    actualTotalTwd: 360,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 80g',
        qty: 2,
        actualLineTwd: 360,
      },
    ],
    refund: null,
    canMerchantRequestRefund: true,
  },
  {
    saleId: 'sale-line-pickup',
    soldAtLabel: '2026-07-18 14:02',
    channel: 'furmosa_collected_line_ecpay',
    channelLabel: 'LINE／綠界付款、門市取貨',
    pickupLabel: '門市取貨',
    statusLabel: '已完成（示意）',
    actualTotalTwd: 390,
    items: [
      {
        name: '雞肉凍乾',
        specLabel: '袋裝 100g',
        qty: 1,
        actualLineTwd: 390,
      },
    ],
    refund: null,
    canMerchantRequestRefund: true,
  },
  {
    saleId: 'sale-refund-requested',
    soldAtLabel: '2026-07-16 09:40',
    channel: 'merchant_collected',
    channelLabel: '店內收款',
    pickupLabel: null,
    statusLabel: '已完成（示意）',
    actualTotalTwd: 280,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 150g',
        qty: 1,
        actualLineTwd: 280,
      },
    ],
    refund: {
      status: 'requested',
      statusLabel: '退款申請中',
      note: '店家已申請，等待總部處理。此頁沒有核准按鈕。',
      nextPeriodNote: null,
      inventoryNote: '庫存處置由總部結果決定，畫面只顯示快照。',
      commissionNote: '佣金回沖以伺服器結果為準，此頁不重算。',
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-refund-approved',
    soldAtLabel: '2026-07-12 16:18',
    channel: 'furmosa_collected_line_ecpay',
    channelLabel: 'LINE／綠界付款、門市取貨',
    pickupLabel: '門市取貨',
    statusLabel: '已完成（示意）',
    actualTotalTwd: 160,
    items: [
      {
        name: '鮭魚薄片',
        specLabel: '單包',
        qty: 1,
        actualLineTwd: 160,
      },
    ],
    refund: {
      status: 'approved',
      statusLabel: '總部已核准',
      note: '這是伺服器結果快照。店家端沒有完成退款按鈕。',
      nextPeriodNote: null,
      inventoryNote: '庫存處置已寫在快照，畫面不重算。',
      commissionNote: '佣金回沖已寫在快照，畫面不重算。',
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-refund-rejected',
    soldAtLabel: '2026-07-10 11:05',
    channel: 'merchant_collected',
    channelLabel: '店內收款',
    pickupLabel: null,
    statusLabel: '已完成（示意）',
    actualTotalTwd: 220,
    items: [
      {
        name: '雞肉凍乾',
        specLabel: '袋裝 50g',
        qty: 1,
        actualLineTwd: 220,
      },
    ],
    refund: {
      status: 'rejected',
      statusLabel: '總部未核准',
      note: '申請未通過。畫面只顯示結果，不會再開新的退款動作。',
      nextPeriodNote: null,
      inventoryNote: '庫存維持原快照。',
      commissionNote: '佣金維持原快照。',
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-refund-completed',
    soldAtLabel: '2026-06-28 13:50',
    channel: 'merchant_collected',
    channelLabel: '店內收款',
    pickupLabel: null,
    statusLabel: '已完成（示意）',
    actualTotalTwd: 480,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 300g',
        qty: 1,
        actualLineTwd: 480,
      },
    ],
    refund: {
      status: 'completed',
      statusLabel: '退款已完成（已結算）',
      note: '這筆退款已進已鎖定結算，不得重開舊結算。',
      nextPeriodNote: '將列入次期調整',
      inventoryNote: '庫存處置以伺服器結果為準。',
      commissionNote: '佣金回沖以伺服器結果為準。',
    },
    canMerchantRequestRefund: false,
  },
];

export const SETTLEMENTS: SettlementSnapshot[] = [
  {
    settlementId: 'stl-draft',
    status: 'draft',
    statusLabel: '草稿',
    periodLabel: '2026年7月1日－7月31日',
    merchantCollectedSalesTwd: 12800,
    furmosaCollectedSalesTwd: 3600,
    ordinaryCommissionSnapshotTwd: 2460,
    voucherFixedSubsidyTwd: 400,
    refundNextPeriodAdjustmentTwd: 0,
    netDirectionLabel: '總部應付店家',
    netAmountTwd: 1540,
    locked: false,
    lockNote: null,
  },
  {
    settlementId: 'stl-reviewing',
    status: 'reviewing',
    statusLabel: '審核中',
    periodLabel: '2026年6月1日－6月30日',
    merchantCollectedSalesTwd: 9800,
    furmosaCollectedSalesTwd: 2100,
    ordinaryCommissionSnapshotTwd: 1785,
    voucherFixedSubsidyTwd: 200,
    refundNextPeriodAdjustmentTwd: 160,
    netDirectionLabel: '總部應付店家',
    netAmountTwd: 355,
    locked: false,
    lockNote: null,
  },
  {
    settlementId: 'stl-approved',
    status: 'approved',
    statusLabel: '已核准',
    periodLabel: '2026年5月1日－5月31日',
    merchantCollectedSalesTwd: 15200,
    furmosaCollectedSalesTwd: 4400,
    ordinaryCommissionSnapshotTwd: 2940,
    voucherFixedSubsidyTwd: 600,
    refundNextPeriodAdjustmentTwd: 280,
    netDirectionLabel: '總部應付店家',
    netAmountTwd: 1780,
    locked: true,
    lockNote: '已鎖定，不可重開；差異走次期調整',
  },
  {
    settlementId: 'stl-paid',
    status: 'paid',
    statusLabel: '已付款',
    periodLabel: '2026年4月1日－4月30日',
    merchantCollectedSalesTwd: 11000,
    furmosaCollectedSalesTwd: 1800,
    ordinaryCommissionSnapshotTwd: 1920,
    voucherFixedSubsidyTwd: 200,
    refundNextPeriodAdjustmentTwd: 0,
    netDirectionLabel: '總部應付店家',
    netAmountTwd: 80,
    locked: true,
    lockNote: '已鎖定，不可重開；差異走次期調整',
  },
];

export const VOUCHER_FACE_BY_TIER: Record<VoucherFaceTier, number> = {
  standard_200: 200,
  zhuwo_250: 250,
};

export const CART_FIXTURE_TOTALS = {
  beef80x2List: 360,
  beef80x2ActualDefault: 360,
  beef80x2Actual170: 340,
  beef80x2Allowance170: 20,
} as const;
