import type { InventoryHistorySnapshot, Product, SaleSnapshot, SettlementSnapshot } from './types';

export const LOW_STOCK_AT = 3;

export const PRODUCTS: Product[] = [
  {
    productId: 'prod-beef',
    name: '原味牛肉條',
    variants: [
      {
        skuId: 'sku-beef-80',
        sku: 'FMT-BEEF-80',
        specLabel: '原味 80g',
        listPriceTwd: 180,
        availableQty: 12,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 6,
        shelfLifeLabel: '未開封 12 個月',
      },
      {
        skuId: 'sku-beef-150',
        sku: 'FMT-BEEF-150',
        specLabel: '原味 150g',
        listPriceTwd: 280,
        availableQty: 3,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 8,
        shelfLifeLabel: '未開封 12 個月',
      },
      {
        skuId: 'sku-beef-300',
        sku: 'FMT-BEEF-300',
        specLabel: '原味 300g',
        listPriceTwd: 480,
        availableQty: 0,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 4,
        shelfLifeLabel: '未開封 12 個月',
      },
    ],
  },
  {
    productId: 'prod-chicken',
    name: '雞肉凍乾',
    variants: [
      {
        skuId: 'sku-chkn-50',
        sku: 'FMT-CHKN-50',
        specLabel: '袋裝 50g',
        listPriceTwd: 220,
        availableQty: 8,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 6,
        shelfLifeLabel: '未開封 10 個月',
      },
      {
        skuId: 'sku-chkn-100',
        sku: 'FMT-CHKN-100',
        specLabel: '袋裝 100g',
        listPriceTwd: 390,
        availableQty: 2,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 5,
        shelfLifeLabel: '未開封 10 個月',
      },
    ],
  },
  {
    productId: 'prod-salmon',
    name: '鮭魚薄片',
    variants: [
      {
        skuId: 'sku-slmn-1',
        sku: 'FMT-SLMN-01',
        specLabel: '單包',
        listPriceTwd: 160,
        availableQty: 0,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 10,
        shelfLifeLabel: '未開封 8 個月',
      },
    ],
  },
  {
    productId: 'prod-cheese',
    name: '起司潔牙棒',
    variants: [
      {
        skuId: 'sku-chee-s',
        sku: 'FMT-CHEE-S',
        specLabel: '小型犬',
        listPriceTwd: 140,
        availableQty: 15,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 4,
        shelfLifeLabel: '未開封 18 個月',
      },
      {
        skuId: 'sku-chee-m',
        sku: 'FMT-CHEE-M',
        specLabel: '中型犬',
        listPriceTwd: 160,
        availableQty: 1,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 6,
        shelfLifeLabel: '未開封 18 個月',
      },
      {
        skuId: 'sku-chee-l',
        sku: 'FMT-CHEE-L',
        specLabel: '大型犬',
        listPriceTwd: 180,
        availableQty: 6,
        lowStockAt: LOW_STOCK_AT,
        suggestedRestockQty: 4,
        shelfLifeLabel: '未開封 18 個月',
      },
    ],
  },
];

export const INVENTORY_HISTORY: Record<string, InventoryHistorySnapshot> = {
  'sku-beef-150': {
    skuId: 'sku-beef-150', periodLabel: '近 90 天', inboundQty: 24, soldQty: 21,
    movements: [
      { movementId: 'mv-b150-1', occurredAtLabel: '2026-08-12', kind: 'sale', kindLabel: '銷售', qty: 4, note: '門市銷售' },
      { movementId: 'mv-b150-2', occurredAtLabel: '2026-08-05', kind: 'inbound', kindLabel: '進貨', qty: 12, note: '補貨到店' },
      { movementId: 'mv-b150-3', occurredAtLabel: '2026-07-24', kind: 'sale', kindLabel: '銷售', qty: 7, note: '門市與取貨訂單' },
      { movementId: 'mv-b150-4', occurredAtLabel: '2026-07-08', kind: 'inbound', kindLabel: '進貨', qty: 12, note: '補貨到店' },
      { movementId: 'mv-b150-5', occurredAtLabel: '2026-06-30', kind: 'sale', kindLabel: '銷售', qty: 10, note: '門市銷售' },
    ],
  },
  'sku-beef-300': {
    skuId: 'sku-beef-300', periodLabel: '近 90 天', inboundQty: 8, soldQty: 8,
    movements: [
      { movementId: 'mv-b300-1', occurredAtLabel: '2026-08-10', kind: 'sale', kindLabel: '銷售', qty: 3, note: '門市銷售' },
      { movementId: 'mv-b300-2', occurredAtLabel: '2026-07-20', kind: 'inbound', kindLabel: '進貨', qty: 4, note: '補貨到店' },
      { movementId: 'mv-b300-3', occurredAtLabel: '2026-07-04', kind: 'sale', kindLabel: '銷售', qty: 5, note: '門市與取貨訂單' },
      { movementId: 'mv-b300-4', occurredAtLabel: '2026-06-18', kind: 'inbound', kindLabel: '進貨', qty: 4, note: '補貨到店' },
    ],
  },
  'sku-chkn-100': {
    skuId: 'sku-chkn-100', periodLabel: '近 90 天', inboundQty: 18, soldQty: 16,
    movements: [
      { movementId: 'mv-c100-1', occurredAtLabel: '2026-08-14', kind: 'sale', kindLabel: '銷售', qty: 5, note: '門市與取貨訂單' },
      { movementId: 'mv-c100-2', occurredAtLabel: '2026-08-01', kind: 'inbound', kindLabel: '進貨', qty: 10, note: '補貨到店' },
      { movementId: 'mv-c100-3', occurredAtLabel: '2026-07-15', kind: 'sale', kindLabel: '銷售', qty: 11, note: '門市銷售' },
      { movementId: 'mv-c100-4', occurredAtLabel: '2026-06-22', kind: 'inbound', kindLabel: '進貨', qty: 8, note: '補貨到店' },
    ],
  },
  'sku-slmn-1': {
    skuId: 'sku-slmn-1', periodLabel: '近 90 天', inboundQty: 20, soldQty: 20,
    movements: [
      { movementId: 'mv-s1-1', occurredAtLabel: '2026-08-15', kind: 'sale', kindLabel: '銷售', qty: 6, note: '門市銷售' },
      { movementId: 'mv-s1-2', occurredAtLabel: '2026-07-28', kind: 'inbound', kindLabel: '進貨', qty: 10, note: '補貨到店' },
      { movementId: 'mv-s1-3', occurredAtLabel: '2026-07-09', kind: 'sale', kindLabel: '銷售', qty: 14, note: '門市與取貨訂單' },
      { movementId: 'mv-s1-4', occurredAtLabel: '2026-06-20', kind: 'inbound', kindLabel: '進貨', qty: 10, note: '補貨到店' },
    ],
  },
  'sku-chee-m': {
    skuId: 'sku-chee-m', periodLabel: '近 90 天', inboundQty: 15, soldQty: 14,
    movements: [
      { movementId: 'mv-cm-1', occurredAtLabel: '2026-08-11', kind: 'sale', kindLabel: '銷售', qty: 5, note: '門市銷售' },
      { movementId: 'mv-cm-2', occurredAtLabel: '2026-07-30', kind: 'inbound', kindLabel: '進貨', qty: 8, note: '補貨到店' },
      { movementId: 'mv-cm-3', occurredAtLabel: '2026-07-12', kind: 'sale', kindLabel: '銷售', qty: 9, note: '門市與取貨訂單' },
      { movementId: 'mv-cm-4', occurredAtLabel: '2026-06-25', kind: 'inbound', kindLabel: '進貨', qty: 7, note: '補貨到店' },
    ],
  },
};

export const SALES: SaleSnapshot[] = [
  {
    saleId: 'sale-cash-open',
    soldAtLabel: '2026-07-18 10:24',
    channel: 'merchant_collected',
    channelLabel: '門市收款',
    pickupLabel: null,
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 360,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 80g',
        qty: 2,
        actualLineTwd: 360,
      },
    ],
    refund: null,
    canMerchantRequestRefund: true,
  },
  {
    saleId: 'sale-line-pickup',
    soldAtLabel: '2026-07-18 14:02',
    channel: 'furmosa_collected_line_ecpay',
    channelLabel: 'LINE／綠界線上收款、門市取貨',
    pickupLabel: '門市取貨',
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 390,
    items: [
      {
        name: '雞肉凍乾',
        specLabel: '袋裝 100g',
        qty: 1,
        actualLineTwd: 390,
      },
    ],
    refund: null,
    canMerchantRequestRefund: true,
  },
  {
    saleId: 'sale-refund-requested',
    soldAtLabel: '2026-07-16 09:40',
    channel: 'merchant_collected',
    channelLabel: '門市收款',
    pickupLabel: null,
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 280,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 150g',
        qty: 1,
        actualLineTwd: 280,
      },
    ],
    refund: {
      status: 'requested',
      statusLabel: '已提出退款申請',
      note: '門市已提出退款申請，等待總部審核。此頁沒有審核按鈕。',
      nextPeriodNote: null,
      inventoryNote: '庫存處置由總部結果決定。',
      commissionNote: '佣金回沖以總部結算結果為準。',
      inventoryDisposition: 'pending',
      conditionLabel: null,
      lossReason: null,
      sellableStockReturned: false,
      settledInLockedPeriod: false,
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-refund-approved',
    soldAtLabel: '2026-07-12 16:18',
    channel: 'furmosa_collected_line_ecpay',
    channelLabel: 'LINE／綠界線上收款、門市取貨',
    pickupLabel: '門市取貨',
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 160,
    items: [
      {
        name: '鮭魚薄片',
        specLabel: '單包',
        qty: 1,
        actualLineTwd: 160,
      },
    ],
    refund: {
      status: 'approved',
      statusLabel: '總部審核通過',
      note: '總部已審核通過。門市端沒有退款完成的按鈕。',
      nextPeriodNote: null,
      inventoryNote: '庫存處置以總部結果為準。',
      commissionNote: '佣金回沖以總部結算結果為準。',
      inventoryDisposition: 'pending',
      conditionLabel: '待總部完成',
      lossReason: null,
      sellableStockReturned: false,
      settledInLockedPeriod: false,
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-refund-rejected',
    soldAtLabel: '2026-07-10 11:05',
    channel: 'merchant_collected',
    channelLabel: '門市收款',
    pickupLabel: null,
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 220,
    items: [
      {
        name: '雞肉凍乾',
        specLabel: '袋裝 50g',
        qty: 1,
        actualLineTwd: 220,
      },
    ],
    refund: {
      status: 'rejected',
      statusLabel: '總部未核准',
      note: '申請未通過。畫面只顯示結果，不會再開新的退款動作。',
      nextPeriodNote: null,
      inventoryNote: '庫存維持原狀。',
      commissionNote: '佣金維持原狀。',
      inventoryDisposition: 'none',
      conditionLabel: null,
      lossReason: null,
      sellableStockReturned: false,
      settledInLockedPeriod: false,
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-o1-restock',
    soldAtLabel: '2026-07-08 15:20',
    channel: 'merchant_collected',
    channelLabel: '門市收款',
    pickupLabel: null,
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 280,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 150g',
        qty: 1,
        actualLineTwd: 280,
      },
    ],
    refund: {
      status: 'completed',
      statusLabel: '退款完成',
      note: '總部已審核並完成退款。未拆封、良好、可再售，已回可售庫存。',
      nextPeriodNote: null,
      inventoryNote: '未拆封、良好、可再售 → 已回可售庫存。',
      commissionNote: '佣金回沖以總部結算結果為準。',
      inventoryDisposition: 'restock_sellable',
      conditionLabel: '未拆封、良好、可再售',
      lossReason: null,
      sellableStockReturned: true,
      settledInLockedPeriod: false,
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-o1-loss',
    soldAtLabel: '2026-07-06 11:40',
    channel: 'furmosa_collected_line_ecpay',
    channelLabel: 'LINE／綠界線上收款、門市取貨',
    pickupLabel: '門市取貨',
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 160,
    items: [
      {
        name: '鮭魚薄片',
        specLabel: '單包',
        qty: 1,
        actualLineTwd: 160,
      },
    ],
    refund: {
      status: 'completed',
      statusLabel: '退款完成',
      note: '總部已審核並完成退款。已拆封／破損，不可再售，不回可售庫存。',
      nextPeriodNote: null,
      inventoryNote: '已拆封／破損／不可售 → 不回可售庫存。',
      commissionNote: '佣金回沖以總部結算結果為準。',
      inventoryDisposition: 'loss_unsellable',
      conditionLabel: '已拆封／破損，不可再售',
      lossReason: '外袋已拆，內容受潮變質',
      sellableStockReturned: false,
      settledInLockedPeriod: false,
    },
    canMerchantRequestRefund: false,
  },
  {
    saleId: 'sale-refund-completed',
    soldAtLabel: '2026-06-28 13:50',
    channel: 'merchant_collected',
    channelLabel: '門市收款',
    pickupLabel: null,
    statusLabel: '已完成（預覽）',
    actualTotalTwd: 480,
    items: [
      {
        name: '原味牛肉條',
        specLabel: '原味 300g',
        qty: 1,
        actualLineTwd: 480,
      },
    ],
    refund: {
      status: 'completed',
      statusLabel: '退款完成（已結算）',
      note: '這筆退款與佣金回沖已列入下期調整，舊期結算不可重新開啟。',
      nextPeriodNote: '將列入下期調整',
      inventoryNote: '庫存處置以總部結果為準。',
      commissionNote: '佣金回沖已列入下期調整，舊期不可重新開啟。',
      inventoryDisposition: 'restock_sellable',
      conditionLabel: '未拆封、良好、可再售',
      lossReason: null,
      sellableStockReturned: true,
      settledInLockedPeriod: true,
    },
    canMerchantRequestRefund: false,
  },
];

export const SETTLEMENTS: SettlementSnapshot[] = [
  {
    settlementId: 'stl-draft',
    status: 'draft',
    statusLabel: '草稿',
    periodLabel: '2026年7月1日－7月31日',
    ledger: [
      {
        rowId: 'stl-draft-audit-merchant-sales',
        label: '門市收款銷售',
        source: '門市收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '門市',
        amountTwd: 12800,
        hqPerspectiveSignedTwd: 0,
        note: '現金已在門市。銷售額只作對帳，不列入應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-draft-audit-official-sales',
        label: 'LINE／綠界線上收款銷售',
        source: 'LINE／綠界線上收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '總部',
        amountTwd: 3600,
        hqPerspectiveSignedTwd: 0,
        note: '銷售額只作對帳。總部義務不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-draft-remit',
        label: '門市應匯總部',
        source: '門市收款結算',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 10880,
        hqPerspectiveSignedTwd: -10880,
        note: '門市扣除可留佣金後應匯總部，不得標為總部應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-draft-official-commission',
        label: 'LINE／綠界線上收款佣金',
        source: 'LINE／綠界線上收款結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 540,
        hqPerspectiveSignedTwd: 540,
        note: '總部對門市的義務是該通路佣金，不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-draft-voucher',
        label: '美容券固定補貼',
        source: '美容服務券結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 400,
        hqPerspectiveSignedTwd: 400,
        note: '美容券固定補貼為總部應付門市。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
    ],
    netDirection: 'merchant_owes_hq',
    netDirectionLabel: '門市應匯總部',
    netAmountTwd: -9940,
    locked: false,
    lockNote: null,
  },
  {
    settlementId: 'stl-reviewing',
    status: 'reviewing',
    statusLabel: '審核中',
    periodLabel: '2026年6月1日－6月30日',
    ledger: [
      {
        rowId: 'stl-reviewing-audit-merchant-sales',
        label: '門市收款銷售',
        source: '門市收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '門市',
        amountTwd: 9800,
        hqPerspectiveSignedTwd: 0,
        note: '現金已在門市。銷售額只作對帳，不列入應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-reviewing-audit-official-sales',
        label: 'LINE／綠界線上收款銷售',
        source: 'LINE／綠界線上收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '總部',
        amountTwd: 2100,
        hqPerspectiveSignedTwd: 0,
        note: '銷售額只作對帳。總部義務不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-reviewing-remit',
        label: '門市應匯總部',
        source: '門市收款結算',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 8330,
        hqPerspectiveSignedTwd: -8330,
        note: '門市扣除可留佣金後應匯總部，不得標為總部應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-reviewing-official-commission',
        label: 'LINE／綠界線上收款佣金',
        source: 'LINE／綠界線上收款結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 315,
        hqPerspectiveSignedTwd: 315,
        note: '總部對門市的義務是該通路佣金，不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-reviewing-voucher',
        label: '美容券固定補貼',
        source: '美容服務券結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 200,
        hqPerspectiveSignedTwd: 200,
        note: '美容券固定補貼為總部應付門市。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-reviewing-refund-clawback',
        label: '本期退款調整',
        source: '已核准退款',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 80,
        hqPerspectiveSignedTwd: -80,
        note: '本期退款調整：門市應匯總部。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-reviewing-next-refund',
        label: '下期退款調整',
        source: '下期調整',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 80,
        hqPerspectiveSignedTwd: 0,
        note: '將列入下期調整，不計入本期結算。',
        periodRoute: 'next_period',
        periodRouteLabel: '下期調整',
      },
    ],
    netDirection: 'merchant_owes_hq',
    netDirectionLabel: '門市應匯總部',
    netAmountTwd: -7895,
    locked: false,
    lockNote: null,
  },
  {
    settlementId: 'stl-approved',
    status: 'approved',
    statusLabel: '已核准',
    periodLabel: '2026年5月1日－5月31日',
    ledger: [
      {
        rowId: 'stl-approved-audit-merchant-sales',
        label: '門市收款銷售',
        source: '門市收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '門市',
        amountTwd: 2000,
        hqPerspectiveSignedTwd: 0,
        note: '現金已在門市。銷售額只作對帳，不列入應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-approved-audit-official-sales',
        label: 'LINE／綠界線上收款銷售',
        source: 'LINE／綠界線上收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '總部',
        amountTwd: 15200,
        hqPerspectiveSignedTwd: 0,
        note: '銷售額只作對帳。總部義務不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-approved-remit',
        label: '門市應匯總部',
        source: '門市收款結算',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 800,
        hqPerspectiveSignedTwd: -800,
        note: '門市扣除可留佣金後應匯總部，不得標為總部應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-approved-official-commission',
        label: 'LINE／綠界線上收款佣金',
        source: 'LINE／綠界線上收款結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 2280,
        hqPerspectiveSignedTwd: 2280,
        note: '總部對門市的義務是該通路佣金，不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-approved-voucher',
        label: '美容券固定補貼',
        source: '美容服務券結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 600,
        hqPerspectiveSignedTwd: 600,
        note: '美容券固定補貼為總部應付門市。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-approved-adj',
        label: '已核准調整',
        source: '已核准調整',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 200,
        hqPerspectiveSignedTwd: 200,
        note: '已核准調整：總部應付門市。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-approved-next',
        label: '下期調整',
        source: '下期調整',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 160,
        hqPerspectiveSignedTwd: 0,
        note: '將列入下期調整，不計入本期結算。',
        periodRoute: 'next_period',
        periodRouteLabel: '下期調整',
      },
    ],
    netDirection: 'hq_owes_merchant',
    netDirectionLabel: '總部應付門市',
    netAmountTwd: 2280,
    locked: true,
    lockNote: '已鎖定，不可重新開啟',
  },
  {
    settlementId: 'stl-paid',
    status: 'paid',
    statusLabel: '已付款',
    periodLabel: '2026年4月1日－4月30日',
    ledger: [
      {
        rowId: 'stl-paid-audit-merchant-sales',
        label: '門市收款銷售',
        source: '門市收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '門市',
        amountTwd: 8000,
        hqPerspectiveSignedTwd: 0,
        note: '現金已在門市。銷售額只作對帳，不列入應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-paid-audit-official-sales',
        label: 'LINE／綠界線上收款銷售',
        source: 'LINE／綠界線上收款',
        kind: 'audit',
        direction: null,
        payer: '顧客',
        payee: '總部',
        amountTwd: 800,
        hqPerspectiveSignedTwd: 0,
        note: '銷售額只作對帳。總部義務不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-paid-remit',
        label: '門市應匯總部',
        source: '門市收款結算',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 6200,
        hqPerspectiveSignedTwd: -6200,
        note: '門市扣除可留佣金後應匯總部，不得標為總部應付。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-paid-official-commission',
        label: 'LINE／綠界線上收款佣金',
        source: 'LINE／綠界線上收款結算',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 120,
        hqPerspectiveSignedTwd: 120,
        note: '總部對門市的義務是該通路佣金，不是線上收款銷售減佣金。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-paid-refund',
        label: '本期退款調整',
        source: '已核准退款',
        kind: 'obligation',
        direction: 'merchant_owes_hq',
        payer: '門市',
        payee: '總部',
        amountTwd: 400,
        hqPerspectiveSignedTwd: -400,
        note: '本期退款調整：門市應匯總部。',
        periodRoute: 'this_period',
        periodRouteLabel: '本期結算',
      },
      {
        rowId: 'stl-paid-next',
        label: '下期調整',
        source: '下期調整',
        kind: 'obligation',
        direction: 'hq_owes_merchant',
        payer: '總部',
        payee: '門市',
        amountTwd: 300,
        hqPerspectiveSignedTwd: 0,
        note: '將列入下期調整，不計入本期結算。',
        periodRoute: 'next_period',
        periodRouteLabel: '下期調整',
      },
    ],
    netDirection: 'merchant_owes_hq',
    netDirectionLabel: '門市應匯總部',
    netAmountTwd: -6480,
    locked: true,
    lockNote: '已鎖定，不可重新開啟',
  },
];

export const CART_FIXTURE_TOTALS = {
  beef80x2List: 360,
  beef80x2ActualDefault: 360,
  beef80x2Actual170: 340,
  beef80x2Allowance170: 20,
} as const;
