-- Rollback for Preview RLS Phase 1 draft
-- Safe: does NOT DELETE/UPDATE business row data.
-- Drops policies, disables RLS, revokes runtime grants, drops helpers.
-- Does NOT drop business tables.
-- May DROP ROLE only if it has no remaining dependencies (manual check).

BEGIN;
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_User" ON "User";
ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "User" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_user_push_subscriptions" ON "user_push_subscriptions";
ALTER TABLE "user_push_subscriptions" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "user_push_subscriptions" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Vendor" ON "Vendor";
ALTER TABLE "Vendor" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Vendor" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Customer" ON "Customer";
ALTER TABLE "Customer" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Customer" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_LineChatSession" ON "LineChatSession";
ALTER TABLE "LineChatSession" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "LineChatSession" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_LineMenuState" ON "LineMenuState";
ALTER TABLE "LineMenuState" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "LineMenuState" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_customer_services" ON "customer_services";
ALTER TABLE "customer_services" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "customer_services" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_jar_codes" ON "jar_codes";
ALTER TABLE "jar_codes" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "jar_codes" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_member_points_ledger" ON "member_points_ledger";
ALTER TABLE "member_points_ledger" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "member_points_ledger" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_refill_orders" ON "refill_orders";
ALTER TABLE "refill_orders" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "refill_orders" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_payment_orders" ON "payment_orders";
ALTER TABLE "payment_orders" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "payment_orders" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_refill_audit_logs" ON "refill_audit_logs";
ALTER TABLE "refill_audit_logs" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "refill_audit_logs" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_reward_catalog" ON "reward_catalog";
ALTER TABLE "reward_catalog" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "reward_catalog" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_reward_redemptions" ON "reward_redemptions";
ALTER TABLE "reward_redemptions" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "reward_redemptions" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_marketing_cost_records" ON "marketing_cost_records";
ALTER TABLE "marketing_cost_records" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "marketing_cost_records" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_stores" ON "stores";
ALTER TABLE "stores" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "stores" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_coupons" ON "coupons";
ALTER TABLE "coupons" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "coupons" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Merchant" ON "Merchant";
ALTER TABLE "Merchant" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Merchant" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_merchant_settings" ON "merchant_settings";
ALTER TABLE "merchant_settings" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "merchant_settings" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_appointments" ON "appointments";
ALTER TABLE "appointments" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "appointments" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_merchant_users" ON "merchant_users";
ALTER TABLE "merchant_users" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "merchant_users" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Warehouse" ON "Warehouse";
ALTER TABLE "Warehouse" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Warehouse" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Product" ON "Product";
ALTER TABLE "Product" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Product" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_ProductPriceTier" ON "ProductPriceTier";
ALTER TABLE "ProductPriceTier" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "ProductPriceTier" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_MerchantProductRule" ON "MerchantProductRule";
ALTER TABLE "MerchantProductRule" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "MerchantProductRule" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Shipment" ON "Shipment";
ALTER TABLE "Shipment" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Shipment" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_restock_requests" ON "restock_requests";
ALTER TABLE "restock_requests" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "restock_requests" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_restock_request_items" ON "restock_request_items";
ALTER TABLE "restock_request_items" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "restock_request_items" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_ShipmentItem" ON "ShipmentItem";
ALTER TABLE "ShipmentItem" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "ShipmentItem" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_MerchantStock" ON "MerchantStock";
ALTER TABLE "MerchantStock" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "MerchantStock" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_MerchantStockTxn" ON "MerchantStockTxn";
ALTER TABLE "MerchantStockTxn" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "MerchantStockTxn" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_InventoryBalance" ON "InventoryBalance";
ALTER TABLE "InventoryBalance" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "InventoryBalance" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_InventoryTransaction" ON "InventoryTransaction";
ALTER TABLE "InventoryTransaction" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "InventoryTransaction" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Order" ON "Order";
ALTER TABLE "Order" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Order" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_OrderItem" ON "OrderItem";
ALTER TABLE "OrderItem" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "OrderItem" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Settlement" ON "Settlement";
ALTER TABLE "Settlement" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Settlement" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_SubscriptionPlan" ON "SubscriptionPlan";
ALTER TABLE "SubscriptionPlan" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "SubscriptionPlan" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Subscription" ON "Subscription";
ALTER TABLE "Subscription" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Subscription" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_SubscriptionShipment" ON "SubscriptionShipment";
ALTER TABLE "SubscriptionShipment" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "SubscriptionShipment" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_Task" ON "Task";
ALTER TABLE "Task" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "Task" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_DashboardKpiSnapshot" ON "DashboardKpiSnapshot";
ALTER TABLE "DashboardKpiSnapshot" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "DashboardKpiSnapshot" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_campaigns" ON "campaigns";
ALTER TABLE "campaigns" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "campaigns" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_campaign_applications" ON "campaign_applications";
ALTER TABLE "campaign_applications" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "campaign_applications" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_ConversationSession" ON "ConversationSession";
ALTER TABLE "ConversationSession" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "ConversationSession" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_conversation_messages" ON "conversation_messages";
ALTER TABLE "conversation_messages" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "conversation_messages" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_order_reviews" ON "order_reviews";
ALTER TABLE "order_reviews" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "order_reviews" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_status_audit_logs" ON "status_audit_logs";
ALTER TABLE "status_audit_logs" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "status_audit_logs" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_refill_flavours" ON "refill_flavours";
ALTER TABLE "refill_flavours" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "refill_flavours" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_merchant_refill_stocks" ON "merchant_refill_stocks";
ALTER TABLE "merchant_refill_stocks" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "merchant_refill_stocks" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_refill_stock_txns" ON "refill_stock_txns";
ALTER TABLE "refill_stock_txns" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "refill_stock_txns" FROM "REPLACE_ME_FURMOSA_RUNTIME";
DROP POLICY IF EXISTS "furmosa_p1_runtime_all_refill_plan_settings" ON "refill_plan_settings";
ALTER TABLE "refill_plan_settings" DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "refill_plan_settings" FROM "REPLACE_ME_FURMOSA_RUNTIME";

DROP FUNCTION IF EXISTS app_rls.current_actor_type();
DROP FUNCTION IF EXISTS app_rls.current_merchant_id();
DROP FUNCTION IF EXISTS app_rls.current_customer_id();
DROP FUNCTION IF EXISTS app_rls.current_line_user_id();
DROP SCHEMA IF EXISTS app_rls;

-- Role drop is optional — only if unused:
-- DROP ROLE IF EXISTS "REPLACE_ME_FURMOSA_RUNTIME";

COMMIT;
