import Link from 'next/link';
import { CheckCircle2, Circle, PackageCheck, Truck } from 'lucide-react';
import { ProductCover } from '@/components/pos/product-cover';

export const metadata = { title: '曼莉莎出貨單示範 · Furmosa POS' };

const items = [
  { id: '1', sku: 'FUR-0022', name: '牛肉丁凍乾', weight: '30g', quantity: 7 },
  { id: '2', sku: 'FUR-0028', name: '水晶魚凍乾', weight: '30g', quantity: 1 },
  { id: '3', sku: 'FUR-0003', name: '混合蔬果凍乾', weight: '30g', quantity: 4 },
  { id: '4', sku: 'FUR-0004', name: '地瓜山藥雞肉月餅', weight: '50g', quantity: 16 },
  { id: '5', sku: 'FUR-0002', name: '原味雞霸', weight: '單包', quantity: 7 },
];
const total = items.reduce((sum, item) => sum + item.quantity, 0);

export default function PreviewManlisaShipmentPage() {
  return <main className="min-h-screen bg-[#f7faf7] px-4 py-6 text-foreground md:px-7 md:py-8"><div className="mx-auto w-full max-w-[1420px]">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-5"><div><p className="text-sm font-semibold text-primary">Furmosa POS · Preview</p><p className="mt-1 text-sm text-muted-foreground">曼莉莎寵物美容</p></div><Link href="/pos/login" className="rounded-xl border border-border bg-card px-4 py-2 text-sm font-medium transition hover:border-primary/40 hover:text-primary">回到登入</Link></div>
    <header className="flex flex-col gap-4 py-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">HQ 補貨配送</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">出貨單 SHP-PREVIEW-0010</h1><p className="mt-2 text-sm text-muted-foreground">商品已由總公司寄出；以下為曼莉莎最新一批的明細示範。</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-amber-300/60 bg-amber-50 px-3.5 py-2 text-sm font-semibold text-amber-800"><span className="h-1.5 w-1.5 rounded-full bg-current" />運送中</span></header>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px] xl:items-start"><section className="overflow-hidden rounded-[24px] border border-border/80 bg-card shadow-[0_18px_48px_rgba(22,50,37,0.07)]"><div className="border-b border-border px-5 py-5 sm:px-7"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold tracking-tight">商品明細</h2><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{items.length} 項商品</span></div><p className="mt-1 text-sm text-muted-foreground">請逐項核對實物、數量與商品狀況。</p></div><div className="hidden grid-cols-[minmax(0,1fr)_84px] gap-4 bg-muted/45 px-7 py-3 text-xs font-medium tracking-wide text-muted-foreground md:grid"><span>商品</span><span className="text-center">數量</span></div><div className="divide-y divide-border">{items.map((item) => <div key={item.id} className="grid gap-4 px-5 py-4 md:grid-cols-[minmax(0,1fr)_84px] md:items-center md:px-7"><div className="flex min-w-0 items-center gap-4"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-2xl bg-[#eef5ef]"><ProductCover name={item.name} imageUrl={null} imgClassName="h-full w-full object-cover" markClassName="flex h-full w-full items-center justify-center bg-primary/10 text-lg font-semibold text-primary" /></div><div className="min-w-0"><p className="truncate font-semibold">{item.name}</p><p className="mt-1 truncate text-xs text-muted-foreground">SKU {item.sku} · {item.weight}</p></div></div><div className="flex items-center justify-between md:justify-center"><span className="text-sm text-muted-foreground md:hidden">數量</span><span className="inline-flex min-w-10 justify-center rounded-full bg-primary/10 px-3 py-1 font-semibold text-primary">× {item.quantity}</span></div></div>)}</div><div className="border-t border-border bg-muted/25 px-5 py-4 text-sm sm:px-7"><span className="text-muted-foreground">合計 <strong className="ml-1 font-semibold text-foreground">{total}</strong> 件</span></div><div className="border-t border-border px-5 py-5 sm:px-7"><div className="flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-primary/10 px-4 text-base font-semibold text-primary"><CheckCircle2 className="h-5 w-5" />Preview 示範 — 正式環境可在此確認入庫</div><p className="mt-3 text-center text-xs text-muted-foreground">示範頁不寫入庫存，也不會影響 HQ 資料。</p></div></section>
      <aside className="space-y-5"><section className="rounded-[24px] border border-border/80 bg-card p-5 shadow-[0_18px_48px_rgba(22,50,37,0.07)]"><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-primary" /><h2 className="text-base font-semibold">出貨資訊</h2></div><dl className="mt-5 divide-y divide-border/70 text-sm"><Info label="出貨單號" value="SHP-PREVIEW-0010" strong /><Info label="發貨單位" value="Furmosa 總公司 HQ" /><Info label="建立日期" value="9月21日 09:30" /><Info label="出貨時間" value="9月21日 10:00" /><Info label="運送方式" value="HQ 配送" /><Info label="物流編號" value="PREVIEW-ONLY" /></dl><div className="mt-5 rounded-2xl bg-muted/60 px-3.5 py-3 text-sm text-muted-foreground"><span className="mb-1 block text-xs font-semibold text-foreground">備註</span>此為 Preview 專用示範資料，不會影響正式庫存。</div></section><section className="rounded-[24px] border border-border/80 bg-card p-5 shadow-[0_18px_48px_rgba(22,50,37,0.07)]"><div className="flex items-center gap-2"><PackageCheck className="h-5 w-5 text-primary" /><h2 className="text-base font-semibold">收貨進度</h2></div><ol className="mt-5 space-y-5"><Step label="完成備貨" date="9月21日 09:30" done /><Step label="商品出貨" date="9月21日 10:00" done /><Step label="物流送達" date="等待處理" /><Step label="店家確認收貨" date="等待處理" last /></ol></section></aside></div>
  </div></main>;
}

function Info({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><dt className="text-muted-foreground">{label}</dt><dd className={`text-right ${strong ? 'font-semibold' : 'font-medium'}`}>{value}</dd></div>; }
function Step({ label, date, done = false, last = false }: { label: string; date: string; done?: boolean; last?: boolean }) { return <li className="relative flex gap-3">{!last ? <span className={`absolute left-[11px] top-6 h-[calc(100%+4px)] w-px ${done ? 'bg-primary/45' : 'bg-border'}`} /> : null}<span className={`relative z-10 flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${done ? 'bg-primary text-primary-foreground' : 'border border-border bg-card text-muted-foreground'}`}>{done ? <CheckCircle2 className="h-4 w-4" /> : <Circle className="h-3 w-3" />}</span><span><span className={`block text-sm font-medium ${done ? 'text-foreground' : 'text-muted-foreground'}`}>{label}</span><span className="mt-1 block text-xs text-muted-foreground">{date}</span></span></li>; }
