export const JIBA_CAMPAIGN_SLUG = 'jiba-two-piece';
export const JIBA_LICENSE_VERSION = 'ugc-v1';
export const JIBA_SHIPPING_FEE = 60;

export const APP_STATUS = {
  COLLECTING_INFO: 'COLLECTING_INFO',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  AWAITING_SHIPPING_PAYMENT: 'AWAITING_SHIPPING_PAYMENT',
  READY_TO_SHIP: 'READY_TO_SHIP',
  REJECTED: 'REJECTED',
  CANCELLED_BY_USER: 'CANCELLED_BY_USER',
  CANCELLED: 'CANCELLED',
} as const;

export type AppStatus = (typeof APP_STATUS)[keyof typeof APP_STATUS];

export const FLOW_STATE = {
  CAMPAIGN_INTRO: 'CAMPAIGN_INTRO',
  SHOW_RULES: 'SHOW_RULES',
  ASK_RECIPIENT_NAME: 'ASK_RECIPIENT_NAME',
  ASK_RECIPIENT_PHONE: 'ASK_RECIPIENT_PHONE',
  ASK_STORE: 'ASK_STORE',
  CONFIRM_STORE: 'CONFIRM_STORE',
  ASK_INSTAGRAM: 'ASK_INSTAGRAM',
  ASK_PET_NAME: 'ASK_PET_NAME',
  ASK_CONTENT_LICENSE: 'ASK_CONTENT_LICENSE',
  SHOW_ORDER_CONFIRMATION: 'SHOW_ORDER_CONFIRMATION',
  EDIT_FIELD_SELECTION: 'EDIT_FIELD_SELECTION',
  PENDING_REVIEW: 'PENDING_REVIEW',
  AWAITING_SHIPPING_PAYMENT: 'AWAITING_SHIPPING_PAYMENT',
  READY_TO_SHIP: 'READY_TO_SHIP',
  CANCELLED: 'CANCELLED',
} as const;

export type FlowState = (typeof FLOW_STATE)[keyof typeof FLOW_STATE];

export const ACTIVE_APP_STATUSES = [
  APP_STATUS.COLLECTING_INFO,
  APP_STATUS.PENDING_REVIEW,
  APP_STATUS.APPROVED,
  APP_STATUS.AWAITING_SHIPPING_PAYMENT,
] as const;

/** 正面參加意圖 */
export const JOIN_INTENT_RE =
  /^(?:我要參加|要|可以|好|來吧|我想參加|怎麼參加|算我一個|敢|敢，來吧|\+1|yes)$/i;

export const DECLINE_RE = /^(?:這次先不要|不要|先不要|我再想一下|先不要送出)$/i;
